In [5]:
import pandas as pd

try:
    entity = pd.read_csv('entity_nsduh.csv', usecols=['id', 'entity_name', 'variable_code'], engine='python', quotechar='"', quoting=1, on_bad_lines='skip')
except pd.errors.ParserError as e:
    print(f"Parsing error: {e}")

In [7]:
entity

          id                  entity_name variable_code
0       1302                    ModeOfUse      MJMONDAB
1          2        PopulationDensity2010        PDEN10
2          3                   CensusData        PDEN10
3          4     CoreBasedStatisticalArea        PDEN10
4          5  OfficeOfManagementAndBudget        PDEN10
...      ...                          ...           ...
10234  10385                     COVID-19    COHCSVHLT2
10235  10386              LanguageVersion       LANGVER
10236  10387       HealthcareAccessImpact       LANGVER
10237  10388             GroupQuarterType       GQTYPE2
10238  10389                 HealthImpact           NaN

[10239 rows x 3 columns]

In [9]:
# Load your DataFrame
clustered_entity = pd.read_csv('2_dbscan_clustered_entities.csv')
# Renaming the column
clustered_entity.rename(columns={'final_cluster': 'cluster_id'}, inplace=True)

In [11]:
clustered_entity

,id,entity_name,entity_description,entity_name_embedding,description_embedding,combined_embedding,dbscan_labels,agg_labels,cluster_id
0,1302,ModeOfUse,"Dabbing waxes, shatter, or concentrate.",[-0.00273205 0.04176282 -0.01434073 ... -0.01...,[ 0.01663675 0.016159 0.01063684 ... -0.05...,[-0.00273205 0.04176282 -0.01434073 ... -0.05...,0,6,DBSCAN_0_AGG_6
1,2,PopulationDensity2010,Population density based on 2010 Census data.,[ 0.04350079 -0.00713865 0.06036023 ... -0.00...,[-0.01276117 -0.00218408 0.06149475 ... -0.02...,[ 0.04350079 -0.00713865 0.06036023 ... -0.02...,-1,9,DBSCAN_-1_AGG_9
2,3,CensusData,Data collected from the 2010 Census.,[-0.01560009 0.02316668 0.06036795 ... -0.01...,[ 0.00514695 0.03145287 0.05214221 ... -0.03...,[-0.01560009 0.02316668 0.06036795 ... -0.03...,-1,9,DBSCAN_-1_AGG_9
3,4,CoreBasedStatisticalArea,Geographical area classification provided by t...,[-0.01456391 -0.01743913 0.08969522 ... -0.03...,[-0.01046925 0.03025889 0.06386418 ... -0.02...,[-0.01456391 -0.01743913 0.08969522 ... -0.02...,-1,9,DBSCAN_-1_AGG_9
4,5,OfficeOfManagementAndBudget,Office that provides Core Based Statistical Ar...,[ 0.01533888 0.00100844 0.01560426 ... -0.01...,[-0.02550434 -0.00333237 0.07938676 ... -0.00...,[ 0.01533888 0.00100844 0.01560426 ... -0.00...,-1,9,DBSCAN_-1_AGG_9
...,...,...,...,...,...,...,...,...,...
10239,10385,COVID-19,COVID-19 pandemic context,[-0.01016783 -0.04450048 -0.01198668 ... 0.01...,[-0.04163803 -0.03421991 0.02700502 ... 0.00...,[-0.01016783 -0.04450048 -0.01198668 ... 0.00...,0,19,DBSCAN_0_AGG_19
10240,10386,LanguageVersion,The language in which the survey was administe...,[-0.0427493 -0.00675749 0.01214379 ... -0.02...,[-0.00752643 0.04435842 0.03043078 ... -0.04...,[-0.0427493 -0.00675749 0.01214379 ... -0.04...,-1,17,DBSCAN_-1_AGG_17
10241,10387,HealthcareAccessImpact,The impact on health due to inability to acces...,[-0.02612596 -0.00102602 0.03334742 ... 0.00...,[ 0.02650863 0.02045722 0.03011008 ... 0.02...,[-0.02612596 -0.00102602 0.03334742 ... 0.02...,0,19,DBSCAN_0_AGG_19
10242,10388,GroupQuarterType,The type of group quarter the respondent is li...,[-0.05111698 0.03824559 0.04207299 ... -0.04...,[-0.01500523 0.01068974 0.06070718 ... -0.03...,[-0.05111698 0.03824559 0.04207299 ... -0.03...,-1,17,DBSCAN_-1_AGG_17
10243,10389,HealthImpact,The impact of inability to access needed care ...,[-0.03134751 0.01311141 0.03170714 ... -0.01...,[ 0.0340832 0.01651688 0.04367134 ... 0.01...,[-0.03134751 0.01311141 0.03170714 ... 0.01...,0,18,DBSCAN_0_AGG_18

In [13]:
# Load your DataFrame
cluster_size= pd.read_csv('cluster_sizes_4.csv')

In [15]:
cluster_size

           cluster_id  num_entities
0     DBSCAN_0_AGG_17          1069
1     DBSCAN_0_AGG_23          1021
2     DBSCAN_0_AGG_38           905
3     DBSCAN_0_AGG_31           761
4     DBSCAN_0_AGG_28           668
..                ...           ...
98   DBSCAN_55_AGG_11             3
99     DBSCAN_7_AGG_9             3
100  DBSCAN_56_AGG_28             3
101  DBSCAN_48_AGG_22             2
102  DBSCAN_28_AGG_24             1

[103 rows x 2 columns]

In [17]:
# Load your DataFrame
final_cluster = pd.read_csv('final_clustered_entities_4.csv')

In [19]:
final_cluster

,id,cluster_id,entity_name,entity_description
0,29,DBSCAN_0_AGG_17,Respondent,The individual who is responding to the survey...
1,41,DBSCAN_0_AGG_17,Respondent,Individual answering the survey.
2,44,DBSCAN_0_AGG_17,SurveyRespondent,Individual responding to the survey question.
3,50,DBSCAN_0_AGG_17,Respondent,The individual providing information about the...
4,61,DBSCAN_0_AGG_17,Individual,A respondent who is part of the survey.
...,...,...,...,...
9794,422,DBSCAN_8_AGG_19,FeeForServicePlan,Type of healthcare coverage
9795,423,DBSCAN_8_AGG_19,SingleServicePlan,Type of healthcare coverage
9796,8488,DBSCAN_48_AGG_22,Plan,A plan to kill oneself.
9797,8498,DBSCAN_48_AGG_22,Plans,Plans made by the adult
9798,5650,DBSCAN_28_AGG_24,Spending Time with Friends and Family,Spending less time with friends and family due...

In [21]:

# Merging the two DataFrames on 'id' column
merged_df = pd.merge(final_cluster, entity[['id', 'variable_code']], on='id', how='left')

# Dropping rows where 'variable_code' is NaN
cleaned_df = merged_df.dropna(subset=['variable_code'])

In [23]:
cleaned_df

,id,cluster_id,entity_name,entity_description,variable_code
0,29,DBSCAN_0_AGG_17,Respondent,The individual who is responding to the survey...,NOMARR2
2,44,DBSCAN_0_AGG_17,SurveyRespondent,Individual responding to the survey question.,ACTD9001
3,50,DBSCAN_0_AGG_17,Respondent,The individual providing information about the...,ACTDVIET
4,61,DBSCAN_0_AGG_17,Individual,A respondent who is part of the survey.,HEALTH
5,67,DBSCAN_0_AGG_17,Person,Individual respondent who provides their feeli...,SEXATRACT
...,...,...,...,...,...
9793,421,DBSCAN_8_AGG_19,HealthMaintenanceOrganization,Type of healthcare coverage,PRVHLTIN
9794,422,DBSCAN_8_AGG_19,FeeForServicePlan,Type of healthcare coverage,PRVHLTIN
9795,423,DBSCAN_8_AGG_19,SingleServicePlan,Type of healthcare coverage,PRVHLTIN
9796,8488,DBSCAN_48_AGG_22,Plan,A plan to kill oneself.,IISUIPLANYR
9797,8498,DBSCAN_48_AGG_22,Plans,Plans made by the adult,IICOSUIPLNYR

In [39]:
# Assuming 'df' is your DataFrame
cleaned_df.to_csv('entity_cluster_with_variable_code.csv', index=False)

# entity as instance

In [41]:
import json
from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import RDF, RDFS, OWL, DCTERMS

# Load JSON data
with open('category.json') as f:
    data = json.load(f)

# Define namespaces
BASE_URI = "http://sail.ua.edu/ruralkg/"
NAMESPACE = Namespace(BASE_URI)

# Initialize RDF Graph
g = Graph()

# Bind namespaces to prefixes
g.bind("base", NAMESPACE)

# Define the ontology URI
ontology_uri = URIRef(BASE_URI + "ontology")

# Declare the ontology and attach metadata
g.add((ontology_uri, RDF.type, OWL.Ontology))
g.add((ontology_uri, DCTERMS.title, Literal("RuralKG Ontology")))
g.add((ontology_uri, DCTERMS.description, Literal("An ontology derived from health dat.")))
g.add((ontology_uri, DCTERMS.creator, Literal("University of Alabama, SAIL Lab, RuralKG Team")))
g.add((ontology_uri, DCTERMS.hasVersion, Literal("0.1.0")))
creation_time = "2024-07-30T12:00:00"
g.add((ontology_uri, DCTERMS.created, Literal(creation_time)))

def process_class(class_data, parent_class=None):
    class_name = class_data["name"].replace(" ", "_").upper()
    class_uri = NAMESPACE[class_name]
    
    if parent_class:
        g.add((class_uri, RDF.type, OWL.Class))
        g.add((class_uri, RDFS.subClassOf, parent_class))
    else:
        g.add((class_uri, RDF.type, OWL.Class))
    
    for var in class_data["vars"]:
        var_name = var.replace(" ", "_").upper()
        var_uri = NAMESPACE[var_name]
        g.add((var_uri, RDF.type, OWL.Class))
        g.add((var_uri, RDFS.subClassOf, class_uri))
        
        # Check if var_name is in source_entity column of relation_df
        if var_name in relation_df['source_entity'].values:
            # Get the related rows
            related_rows = relation_df[relation_df['source_entity'] == var_name]
            for _, row in related_rows.iterrows():
                relation = row['relationship']
                target_entity_name = row['target_entity'].replace(" ", "_").upper()
                target_entity_uri = NAMESPACE[target_entity_name]
                relation_uri = NAMESPACE[relation]
                
                # Add the relationship triple
                g.add((var_uri, relation_uri, target_entity_uri))
    
    for child in class_data["child_classes"]:
        process_class(child, class_uri)

# Process each top-level class
for entry in data:
    process_class(entry)

# Serialize the RDF graph to a TTL file
output_file = 'entity_as_instance_with_relation.ttl'
g.serialize(destination=output_file, format='turtle')

# Entity as class

In [13]:
# Load JSON data
with open('category.json') as f:
    data = json.load(f)

# Define namespaces
BASE_URI = "http://sail.ua.edu/ruralkg/"
NAMESPACE = Namespace(BASE_URI)

# Initialize RDF Graph
g = Graph()

# Bind namespaces to prefixes
g.bind("base", NAMESPACE)

# Define the ontology URI
ontology_uri = URIRef(BASE_URI + "ontology")

# Declare the ontology and attach metadata
g.add((ontology_uri, RDF.type, OWL.Ontology))
g.add((ontology_uri, DCTERMS.title, Literal("RuralKG Ontology")))
g.add((ontology_uri, DCTERMS.description, Literal("An ontology derived from health dat.")))
g.add((ontology_uri, DCTERMS.creator, Literal("University of Alabama, SAIL Lab, RuralKG Team")))
g.add((ontology_uri, DCTERMS.hasVersion, Literal("0.1.0")))
creation_time = "2024-07-30T12:00:00"
g.add((ontology_uri, DCTERMS.created, Literal(creation_time)))

def process_class(class_data, parent_class=None):
    class_name = class_data["name"].replace(" ", "_").upper()
    class_uri = NAMESPACE[class_name]
    
    if parent_class:
        g.add((class_uri, RDF.type, OWL.Class))
        g.add((class_uri, RDFS.subClassOf, parent_class))
    else:
        g.add((class_uri, RDF.type, OWL.Class))
    
    for var in class_data["vars"]:
        var_name = var.replace(" ", "_").upper()
        var_uri = NAMESPACE[var_name]
        g.add((var_uri, RDF.type, OWL.Class))
        g.add((var_uri, RDFS.subClassOf, class_uri))
    
    for child in class_data["child_classes"]:
        process_class(child, class_uri)

# Process each top-level class
for entry in data:
    process_class(entry)

# Serialize the RDF graph to a TTL file
output_file = 'entity_as_class.ttl'
g.serialize(destination=output_file, format='turtle')
print(f"RDF graph serialized and saved to {output_file}.")

RDF graph serialized and saved to entity_as_class.ttl.

# Feed data

In [4]:
import psycopg2
from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import RDF, XSD, RDFS, OWL, DCTERMS
from tqdm import tqdm

import pandas as pd

In [6]:

# Connect to the PostgreSQL database
conn = psycopg2.connect(
    host='127.0.0.1',
    dbname='ethan',
    user='postgres',
    password='950623',
    port='5432'
)
cursor = conn.cursor()

In [10]:
    # Execute a SELECT query
    cursor.execute("SELECT city_id, city_name, county_id, state_id, latitude, longitude, year, population, ranking, density, incorporated, zips FROM public.city;")  # Replace with your actual query

    # Fetch the results
    rows = cursor.fetchall()

    # Print the results
    for row in rows:
        print(row)

    # Close the cursor and connection
    cursor.close()
    conn.close()
    print("Connection closed")

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [27]:
import pandas as pd

relation_df = pd.read_csv('./entity_rel_extraction_final/1_relationships.csv')

In [29]:
relation_df

,relationship,source_entity,target_entity,question_code,description
0,isBasedOn,PopulationDensity2010,CensusData,PDEN10,Population density is based on 2010 Census data.
1,isClassifiedBy,PopulationDensity2010,CoreBasedStatisticalArea,PDEN10,Population density is classified by the Core B...
2,providedBy,CoreBasedStatisticalArea,OfficeOfManagementAndBudget,PDEN10,Core Based Statistical Area classifications ar...
3,isClassifiedBy,CountyMetroNonMetroStatus,RuralUrbanContinuumCodes,COUTYP4,The metro or non-metro status of the county is...
4,hasType,American Indian Areas (AIAs),Federally-recognized American Indian reservati...,MAIIN102,Federally recognized American Indian reservati...
...,...,...,...,...,...
8020,contextOf,HealthcareAccess,COVID-19,COHCSVHLT2,Lack of access to medical care is contextualiz...
8021,hasVersion,Survey,LanguageVersion,LANGVER,Relates the survey to the specific language ve...
8022,impactsHealth,HealthcareAccess,HealthcareAccessImpact,LANGVER,Relates the access to healthcare to its impact...
8023,impactsHealth,AccessToCare,HealthImpact,GQTYPE2,Describes the effect of not being able to acce...
8024,categorizedBy,GroupQuarter,GroupQuarterType,GQTYPE2,Specifies the category of the type of group qu...

In [37]:
# Creating a copy of the cleaned DataFrame
cleaned_df_copy = cleaned_df.copy()
cleaned_df_copy['relationship'] = None

# Iterating through cleaned_df
for i, cleaned_row in cleaned_df.iterrows():
    # Filter relation_df to find matches for variable_code
    matched_relations = relation_df[relation_df['question_code'] == cleaned_row['variable_code']]
    
    for j, relation_row in matched_relations.iterrows():
        if cleaned_row['entity_name'] in [relation_row['source_entity'], relation_row['target_entity']]:
            cleaned_df_copy.at[i, 'relationship'] = relation_row['relationship']
            break

In [39]:
cleaned_df_copy

,id,cluster_id,entity_name,entity_description,variable_code,relationship
0,29,DBSCAN_0_AGG_17,Respondent,The individual who is responding to the survey...,NOMARR2,hasMaritalHistory
2,44,DBSCAN_0_AGG_17,SurveyRespondent,Individual responding to the survey question.,ACTD9001,hasActiveDutyPeriod
3,50,DBSCAN_0_AGG_17,Respondent,The individual providing information about the...,ACTDVIET,servedDuring
4,61,DBSCAN_0_AGG_17,Individual,A respondent who is part of the survey.,HEALTH,hasOverallHealth
5,67,DBSCAN_0_AGG_17,Person,Individual respondent who provides their feeli...,SEXATRACT,feelsSexualAttractionTowards
...,...,...,...,...,...,...
9793,421,DBSCAN_8_AGG_19,HealthMaintenanceOrganization,Type of healthcare coverage,PRVHLTIN,includes
9794,422,DBSCAN_8_AGG_19,FeeForServicePlan,Type of healthcare coverage,PRVHLTIN,includes
9795,423,DBSCAN_8_AGG_19,SingleServicePlan,Type of healthcare coverage,PRVHLTIN,includes
9796,8488,DBSCAN_48_AGG_22,Plan,A plan to kill oneself.,IISUIPLANYR,hasMadePlans
9797,8498,DBSCAN_48_AGG_22,Plans,Plans made by the adult,IICOSUIPLNYR,madePlans